<?php

namespace AppBundle\Repository;

/**
 * EintragRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EintragRepository extends \Doctrine\ORM\EntityRepository
{
}
